apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-api-secrets-vault
  namespace: demo
spec:
  secretStoreRef:
    name: vault-kv
    kind: SecretStore
  target:
    name: demo-api                 # K8s Secret your app/Helm reads
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: DB_PASSWORD       # key inside the K8s Secret
      remoteRef:
        key: app/demo              # KV path under 'kv' (i.e., kv/data/app/demo)
        property: db_password
