apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-api-secrets
  namespace: demo
spec:
  secretStoreRef:
    name: aws-sm
    kind: SecretStore
  target:
    name: demo-api        # the K8s Secret name your app/Helm reads
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: DB_PASSWORD           # key inside the K8s Secret
      remoteRef:
        key: prod/demo-api             # name/ARN in AWS SM
        property: db_password
